language: java
jdk: openjdk8

dist: trusty

before_install:
  - chmod +x gradle/wrapper/gradle-wrapper.jar

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)

